name: recipe_on_net
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  build_runner: ^2.4.13
  cached_network_image: ^3.4.1
  cloud_firestore: ^4.17.5
  dio: ^5.7.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.5
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.5
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.2.2
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Klasik
      fonts:
        - asset: assets/fonts/Klasik-Regular.otf
        - asset: assets/fonts/Klasik-Rough.otf
        - asset: assets/fonts/Klasik-Shadow.otf

  assets:
    - assets/
    - assets/logo/
    - assets/illustrations/
    - assets/icons/
